server:
  port: 2301
# 开启端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

#设置ribbon的超时时间
ribbon:
  # 连接超时时间
  ConnectTimeout: 3000
  ReadTimeout: 5000


# 配置openfeign日志
logging:
  level:
    com.cloud.alibaba.feign: debug



