server:
  port: 2301
# 开启端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
# SpringCloud配置
spring:
  application:
    name: order-nacos
  cloud:
    #nacos配置
    nacos:
      #nacos的ip:端口
      server-addr: 192.168.184.100:7747
      discovery:
        # nacos用户名
        username: nacos
        # nacos密码
        password: nacos
        # nacos命名空间
        namespace: public
        # nacos的分组
        group: DEFAULT_GROUP
  main:
    allow-bean-definition-overriding: true    #不然多个feign接口连接相同的微服务则会报错

#设置ribbon的超时时间
ribbon:
  # 连接超时时间
  ConnectTimeout: 3000
  ReadTimeout: 5000


# 配置openfeign日志
logging:
  level:
    com.cloud.alibaba.feign: debug